routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\Auth::user()) {
        return redirect('/home');
    } else {
        return view('welcome');
    }

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/save-wallet', 'HomeController@saveWallet')->name('save-wallet');
Route::post('/get-bank-wallet', 'HomeController@getBankWallet')->name('get-bank-wallet');
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');
Route::get('confirm-wallet/{token}', 'HomeController@confirmWallet')->name('confirm_wallet');

Route::middleware('admin')->group(function () {
    Route::namespace('Admin')->group(function () {

        Route::prefix('admin')->group(function () {

            Route::get('/', 'AdminController@index')->name('admin');
            Route::get('/transfers', 'TransferController@index')->name('transfers');
            Route::get('/currencies', 'AdminController@currencies')->name('currencies');
            Route::post('/accept_currency', 'AdminController@acceptCurrency');
            Route::post('/active-stage', 'AdminController@activeStage');


            Route::prefix('volume')->group(function() {
                Route::get('/', 'VolumeController@index')->name('volume');
                Route::post('/', 'VolumeController@store')->name('volume-save');
            });


            Route::prefix('stages')->group(function () {
                Route::get('/', 'StageController@index')->name('stages');
                Route::get('/edit/{id}', 'StageController@edit')->name('stage-edit');
                Route::get('/create', 'StageController@create')->name('stage-create');
                Route::post('/update', 'StageController@update')->name('stage-update');
                Route::post('/store', 'StageController@store')->name('stage-store');
                Route::post('/delete/{stage}', 'StageController@delete')->name('stage-delete');
            });

            Route::prefix('users')->group(function () {
                Route::get('/', 'UserController@index')->name('users');
                Route::get('/{id}', 'UserController@show')->name('users-show');
            });

        });


    });
});

app/Models/Accounts/Account.php
<?php

namespace App\Models\Accounts;

use App\Models\Auth\User;
use BaconQrCode\Renderer\Image\Png;
use BaconQrCode\Writer;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * @property integer id
 * @property Currency currency
 * @property float balance
 * @property User user
 * @property string wallet
 * @property bool is_active
 * @property integer user_id
 * @property string status
 * @property float actual_balance
 * @property float pending_balance
 * @property float credit_limit
 */
class Account extends Model
{
    const STATUS_CREATED = 'created';
    const STATUS_OPEN = 'open';
    const STATUS_CLOSED = 'closed';

    const STATUSES = [
        self::STATUS_CREATED,
        self::STATUS_OPEN,
        self::STATUS_CLOSED,
    ];

    const TYPE_BANK_PAYMENT = 'bank_payment';
    const TYPE_USER_ETHER = 'user_ether';
    const TYPE_USER_ETHER_OLD = 'user_ether_old';
    const TYPE_COIN_SOURCE = 'coin_source';
    const TYPE_SELLER_COIN = 'seller_coin';
    const TYPE_TOKEN_SOURCE = 'token_source';
    const TYPE_USER_TOKEN = 'user_token';

    const TYPES = [
        self::TYPE_BANK_PAYMENT,
        self::TYPE_USER_ETHER,
        self::TYPE_USER_ETHER_OLD,
        self::TYPE_COIN_SOURCE,
        self::TYPE_SELLER_COIN,
        self::TYPE_TOKEN_SOURCE,
        self::TYPE_USER_TOKEN,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'type',
        'status',
        'user_id',
        'currency_id',
        'balance',
        'credit_limit',
        'updated_at',
    ];

    ///////////////
    // Relations //
    ///////////////

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user() {
        return $this->belongsTo('App\Models\Auth\User');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function currency() {
        return $this->belongsTo('App\Models\Accounts\Currency');
    }

    public function transactions() {
        return $this->hasMany('App\Models\Accounts\Transaction');
    }

    ////////////////
    // Attributes //
    ////////////////

    public function getQrBase64Attribute()
    {
        if (!$this->wallet) {
            return '';
        }
        $renderer = new Png();
        $renderer->setHeight(136);
        $renderer->setWidth(136);
        $renderer->setMargin(0);
        $writer = new Writer($renderer);
        return 'data:image/png;base64,' . base64_encode($writer->writeString($this->wallet));
    }

    public function getActualBalanceAttribute()
    {
        return $this->transactions()->sum('amount');
    }

    /////////////
    // Methods //
    /////////////

    /**
     * @return bool
     */
    public function isOpen() {
        return $this->status === self::STATUS_OPEN;
    }

    /**
     * @param User $user
     * @return bool
     */
    public function canBeAuthorisedBy(User $user=null) {
        if ($user === null) {
            return true;
        }
        return !$this->user || $user->id === $this->user->id || $this->credit_limit === null;
    }

    /**
     * @param double $amount Sum to debit.
     * @return bool
     */
    public function isDebitPermitted($amount) {
        if ($this->credit_limit === null) {
            return true;
        }
        $available = bcadd($this->actual_balance, $this->credit_limit, 20);
        return bccomp($available, $amount, 20) >= 0;
    }

    public function getBalanceRoundAttribute()
    {
        $balance = floatval($this->balance);

        if ($balance == 0) {
            return 0;
        } else {
            if ($balance * 10 * 1000 >= 0.1) {
                return number_format($balance, 5);
            } else {
                return round($balance, 4);
            }
        }
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Accounts\Stage;
use App\Models\Accounts\Transfer;
use App\Models\Auth\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    public function show($id)
    {
        $user = User::with(['referrals', 'referrer'])->find($id);
        $transfers = $user->transfers;
        $accounts = $user->accounts;
        return view('admin.users.show', compact('transfers', 'user', 'accounts'));
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Users</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">email</th>
            <th scope="col">ETH wallet</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{$user->email}}</td>
                <td>{{ old('wallet') ?: ($user->ether_account ? $user->ether_account->wallet : '')}}</td>
                <td><a href="{{route('users-show', ['id' => $user->id])}}" class="btn btn-info">Показать</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.admin')

@section('content')
    <h1>User info: {{$user->email}}</h1>
    <hr>
    @if (! is_null($user->referrer))
        <h2>Referrer: <a href="{{ route('users-show', ['id' => $user->referrer->id]) }}">{{ $user->referrer->email }}</a></h2>
        <hr />
    @endif
    <h2>Transfers</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">type</th>
            <th scope="col">amount</th>
            <th scope="col">date</th>
            <th scope="col">reference</th>
        </tr>
        </thead>
        <tbody>
        @foreach($transfers as $transfer)
            <tr>
                <td>{{$transfer->type}}</td>
                <td>
                    {{$transfer->type == \App\Models\Accounts\Transfer::TYPE_COIN_SPENDING ? '-' : ''}}{{$transfer->amount}}
                    {{$transfer->source->currency->code}}
                </td>
                <td>{{$transfer->created_at}}</td>
                <td>{{$transfer->reference}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <h2>Accounts</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">code</th>
            <th scope="col">wallet</th>
            <th scope="col">balance</th>
        </tr>
        </thead>
        <tbody>
        @foreach($accounts as $account)
            <tr>
                <td>{{$account->currency->code}}</td>
                <td>{{$account->wallet}}</td>
                <td>{{$account->balance_round}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    @if ($user->referrals->count() > 0)
    <h2>Referrals</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">email</th>
            <th scope="col">name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($user->referrals as $referral)
            <tr>
                <td><a href="{{route('users-show', ['id' => $referral->id])}}">{{$referral->email}}</td>
                <td>{{$referral->name}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif
@endsection